## Fréquences de taille géo-référencées {#SF}

#### Description

Estimations mensuelles des fréquences de taille des captures conservées à bord et rejetées par flotte de pêche, pêcherie, carré statistisque de 5&deg; de longitude et latitude, espèce et sexe.

#### Mesures de Conservation et de Gestion

- Rés. [15/01](https://iotc.org/fr/mcg/r%C3%A9solution-1501-concernant-l%E2%80%99enregistrement-des-captures-et-de-l%E2%80%99effort-par-les-navires-de-p%C3%AAche) (Annex II) -- _Concernant l’enregistrement des captures et de l’effort par les navires de pêche dans la zone de compétence de la CTOI_
- Rés. [15/02](https://iotc.org/fr/mcg/r%C3%A9solution-1502-d%C3%A9clarations-statistiques-exigibles-des-parties-contractantes-et-parties) (para. 2) -- _Déclarations statistiques exigibles des parties contractantes et parties coopérantes non contractantes (CPC) de la CTOI_
- Rés. [17/05](https://iotc.org/fr/mcg/r%C3%A9solution-1705-%E2%80%A8sur-la-conservation-des-requins-captur%C3%A9s-en-association-avec-des-p%C3%AAcheries) (para. 6) -- _Sur la conservation des requins capturés en association avec des pêcheries gérées par la CTOI_
- Rés. [18/02](https://iotc.org/fr/mcg/r%C3%A9solution-1802-sur-des-mesures-de-gestion-pour-la-conservation-des-requins-peau-bleue-captur%C3%A9s) (para. 3) -- _Sur des mesures de gestion pour la conservation des requins peau bleue capturés en association avec les pêcheries de la CTOI_
- Rés. [18/05](https://iotc.org/fr/mcg/r%C3%A9solution-1805-sur-des-mesures-de-gestion-pour-la-conservation-des-poissons-porte-%C3%A9p%C3%A9es-marlin) (para. 8) -- _Sur des mesures de gestion pour la conservation des poissons porte-épées : marlin rayé, marlin noir, marlin bleu et voilier indopacifique_

#### Contenu

Mesures des tailles individuelles des poissons pour les espèces de la CTOI, les requins communs et les autres espèces faisant l'objet de prises accessoires. Les mesures de longueur droites effectuées à l'aide d'un pied à coulisse ou d'une planche à mesurer sont recommandées plutôt que le poids des poissons et varient en fonction des groupes de poissons : (i) [longueur de la fourche de la mâchoire inférieure](#lj) pour les istiophoridés, (ii) [longueur de la fourche de la mâchoire supérieure](#uj) pour les thonidés, les maquereaux, les requins et toutes les autres espèces de poissons de capture ayant une queue fourchue ou lunaire, (iii) [longueur standard](#sl) pour les espèces de poissons de capture ayant une queue arrondie ou tronquée, et (iv) [largeur du disque](#dw) pour les raies. Le Secrétariat recommande en outre l'utilisation d'intervalles de longueur pour les espèces de la CTOI et les requins les plus couramment capturés, ainsi que des intervalles de longueur maximum et des plages de valeurs valides qui sont utilisés pour filtrer et consolider les jeux de données de fréquences de taille mis à disposition pour soutenir le processus de la CTOI (voir [Mesures recommandées](../domaine/biologique/#morphometricsRecommended)).

La couverture de l'échantillonnage est fixée à au moins un (1) poisson mesuré par tonne capturée par pêcherie et par espèce, les échantillons étant représentatifs de toutes les périodes et zones de pêche. Pour chaque strate, la couverture des données - c'est-à-dire le pourcentage (%) des captures/efforts échantillonnés - dérivée du type de couverture doit être déclarée afin d'évaluer la représentativité et la qualité des estimations. En outre, des estimations majorées de la taille des échantillons doivent être communiquées au secrétariat afin de tenir compte des biais dus à un échantillonnage non représentatif. Des documents couvrant les procédures d'échantillonnage et d'augmentation doivent être fournis pour chaque pêcherie et chaque espèce.

#### Métadonnées de déclaration

- [Nom complet du point de contact](#fcname)
- [Adresse électronique du point de contact](#fcemail)
- [Nom de l'organisation](#orgname)
- [Adresse électronique de l'organisation](#orgemail)
- [Date de finalisation](#findate)
- [Date de soumission](#subdate)
- [Année de déclaration](#repyear)
- [Entité déclarante](#repentity)
- [État du pavillon](#repflagstate)

#### Dimensions des données

##### Strate principale

- Mois
- [Grilles](../domain/admin/#IOTCgridsCESF)
- [Espèces](../domain/biological/#allSpecies)
- [Sexes](..domain/biological/#sex)
- [Types de devenir](../domain/biological/#typesOfFate)
- [Devenirs](../domain/biological/#fates)

##### Données originales

- [Types de données](../domain/data/#types)
- [Sources des données](../domain/data/#sourcesSF)
- [Traitements des données](../domain/data/#processingsSF)

##### Couverture

- [Estimations](../domain/data/#estimations)
- [Types d'indicateur de couverture](../domain/data/#coverageTypes)
- [Extrapolations](../domain/data/#raisings)

##### Mensuration

- [Types de mensuration](../domain/biological/#typesOfMeasurement)
- [Mensurations](../domain/biological/#allMeasurementTypes)
- [Outils](../domain/biological/#allMeasurementTools)

#### Détails du formulaire de déclaration

Formulaire [4SF](../forms/#Form_4SF)

<hr style="border:1.5px solid black">
