## Captures et efforts de pêche géo-référencés {#CE}

#### Description

Estimations des captures et des efforts de pêche par espèce, flotte de pêche, pêcherie et strate spatio-temporelle, incluant l'effort exercé par les navires auxiliaires assistant les senneurs. 

#### Mesures de Conservation et de Gestion

- Rés. [15/01](https://iotc.org/fr/mcg/r%C3%A9solution-1501-concernant-l%E2%80%99enregistrement-des-captures-et-de-l%E2%80%99effort-par-les-navires-de-p%C3%AAche) (Annex II) -- _Concernant l’enregistrement des captures et de l’effort par les navires de pêche dans la zone de compétence de la CTOI_
- Rés. [15/02](https://iotc.org/fr/mcg/r%C3%A9solution-1502-d%C3%A9clarations-statistiques-exigibles-des-parties-contractantes-et-parties) (para. 2) -- _Déclarations statistiques exigibles des parties contractantes et parties coopérantes non contractantes (CPC) de la CTOI_
- Rés. [17/05](https://iotc.org/fr/mcg/r%C3%A9solution-1705-%E2%80%A8sur-la-conservation-des-requins-captur%C3%A9s-en-association-avec-des-p%C3%AAcheries) (para. 6) -- _Sur la conservation des requins capturés en association avec des pêcheries gérées par la CTOI_
- Rés. [18/02](https://iotc.org/fr/mcg/r%C3%A9solution-1802-sur-des-mesures-de-gestion-pour-la-conservation-des-requins-peau-bleue-captur%C3%A9s) (para. 3) -- _Sur des mesures de gestion pour la conservation des requins peau bleue capturés en association avec les pêcheries de la CTOI_
- Rés. [18/05](https://iotc.org/fr/mcg/r%C3%A9solution-1805-sur-des-mesures-de-gestion-pour-la-conservation-des-poissons-porte-%C3%A9p%C3%A9es-marlin) (para. 8) -- _Sur des mesures de gestion pour la conservation des poissons porte-épées : marlin rayé, marlin noir, marlin bleu et voilier indopacifique_

##### Interdictions de rétention dans les pêcheries [de palangre](#iotclonglinefishery) et [de surface](#iotcsurfacefishery)

- Rés. [12/09](https://iotc.org/fr/mcg/r%C3%A9solution-1209-sur-la-conservation-des-requins-renards-famille-des-alopiid%C3%A6-captur%C3%A9s-par-les) -- _Sur la conservation des requins-renards (famille des Alopiidæ) capturés par les pêcheries dans la zone de compétence de la CTOI_
- Rés. [13/06](https://iotc.org/fr/mcg/r%C3%A9solution-1306-sur-un-cadre-scientifique-et-de-gestion-pour-la-conservation-des-requins) -- _Sur un cadre scientifique et de gestion pour la conservation des requins capturés en association avec des pêcheries gérées par la CTOI_
- Rés. [19/03](https://iotc.org/fr/mcg/r%C3%A9solution-1903-sur-la-conservation-des-raies-mobulidae-captur%C3%A9es-en-association-avec-les) -- _Sur la conservation des raies Mobulidae capturées en association avec les pêcheries dans la zone de compétence de la CTOI_

#### Contenu

- Estimations des efforts exprimés en unités conformes aux exigences établies dans la Résolution [15/01](https://iotc.org/fr/mcg/r%C3%A9solution-1501-concernant-l%E2%80%99enregistrement-des-captures-et-de-l%E2%80%99effort-par-les-navires-de-p%C3%AAche) pour les [pêcheries palangrières](#iotclonglinefishery) et les [pêcheries de surface](#iotcsurfacefishery), complétées par les nombres d'opérations de pêche suivant une recommandation du SC ([IOTC-2022-SC25-R](https://iotc.org/documents/SC/25/RE)). Pour les pêcheries côtières, il est recommandé de soumettre les donnés d'efforts dans les mêmes unités que celles prescriptes pour les pêcheries de surface caractérisées par les mêmes engins de pêche. 

| Groupe d'engins | Effort primaire | Effort secondaire |
| :---------------- | :---------------------- | :--------------------- |
Filets maillants (GI)   | Nombre de jours de pêche | Nombre d'opérations de pêche |
Hameçons et lignes (HL) | Nombre de jours de pêche | Nombre d'hameçons deployés |
Palangres (LL) | Nombre d'hameçons deployés | Nombre d'opérations de pêche |
Autres engins (OT) | Nombre de jours en mer | Nombre d'opérations de pêche |
Cannes (PL) | Nombre de jours de pêche | Nombre d'opérations de pêche |
Sennes coulissantes (PS) | Nombre d'heures de pêche | Nombre d'opérations de pêche |

L'utilisation des marées comme unité d'effort n'est **pas recommandée** car la durée des marées peut varier considérablement en fonction de la longueur du navire, du succès de la pêche et de multiples facteurs techniques (p. ex. disponbilité de carburant).

Des unités supplémentaires peuvent être envisagées pour affiner et normaliser l'estimation de l'effort de pêche nominal :

i. Dans les pêcheries au filet maillant, la surface des filets déployés peut mieux refléter l'intensité de l'effort en tenant compte des différences de longueur et de hauteur des filets ;

ii. Dans les pêcheries à lignes et hameçons, le nombre d'hameçons peut être utilisé comme requis pour les pêcheries à la palangre ;

iii. Dans les pêcheries à la canne, le nombre de cannes journalières utilisées peut aider à tenir compte des différences dans le nombre de pêcheurs présents à bord des navires ;

iv. Dans les pêcheries à senne coulissante, le nombre d'opérations de pêche réussies et nulles, le temps de recherche et la surface explorée peuvent compléter les informations fournies par le temps de pêche et le nombre total de calées.

- Estimations des captures pour les espèces de la CTOI, les requins communs et autres espèces de prises accessoires. L'extrapolation aux totaux mensuels des captures nationales est obligatoire (M) pour les [pêcheries palangrières](#iotclonglinefishery) et les [pêcheries de surface](#iotcsurfacefishery) et facultative (O) pour les [pêcheries côtières](#iotccoastalfishery).

Pour chaque strate, la couverture des données - c'est-à-dire le pourcentage (%) des captures/efforts échantillonnés - provenant du type de couverture doit être déclarée afin d'évaluer la représentativité et la qualité des estimations. Les résolutions spatiales et temporelles, les unités de capture et le niveau d'extrapolation varient en fonction de la catégorie de pêche.

| Catégorie | Résolution temporelle | Résolution spatiale | Unité de capture | Extrapolation | 
| :------------ | :---------- | :---------- | :------------- | :-------: |
[Pêcheries de surface](#iotcsurfacefishery)  | Mois | [1° zone quadrillée](../domain/admin/#IOgrids1x1) | Equivalent poids vif | M |
[Pêcheries palangrières](#iotclonglinefishery) | Mois ou plus précis pour le CS | [5° zone quadrillée](../domain/admin/#IOgrids5x5) ou plus précis pour le CS | Nombre ou équivalent poids vif | M |
[Pêcheries côtières](#iotccoastalfishery) | Année ou plus précis | [Zones irrégulières](../domain/admin/#IOTCareasAR) | Nombre ou équivalent poids vif | O |

La documentation décrivant les procédures d'extrapolation (y compris les taux d'extrapolation pour la couverture des livres de bord) est également requise et doit être soumise régulièrement (Rés. [15/02](https://iotc.org/fr/mcg/r%C3%A9solution-1502-d%C3%A9clarations-statistiques-exigibles-des-parties-contractantes-et-parties); para. 4). Un modèle de déclaration des informations sur les procédures d'échantillonnage est disponible dans le document  [IOTC-2021-WPDCS17-27](https://www.iotc.org/WPDCS/17/27).

#### Métadonnées de déclaration

- [Nom complet du point de contact](#fcname)
- [Adresse électronique du point de contact](#fcemail)
- [Nom de l'organisation](#orgname)
- [Adresse électronique de l'organisation](#orgemail)
- [Date de finalisation](#findate)
- [Date de soumission](#subdate)
- [Année de déclaration](#repyear)
- [Entité déclarante](#repentity)
- [État du pavillon](#repflagstate)

#### Dimensions des données

##### Principaux éléments des captures

- Mois
- [Pêcheries](../domain/fisheries/#fisheries)
- [Grilles](../domain/admin/#IOTCgridsCESF)
- [Estimations](../domain/data/#estimations)
- [Espèces](../domain/biological/#allSpecies)  
- [Unités de capture](../domain/fisheries/#catchUnits)

##### Principaux éléments des efforts

- Mois
- [Pêcheries](../domain/fisheries/#fisheries)
- [Grilles](../domain/admin/#IOTCgridsCESF)
- [Estimations](../domain/data/#estimations)
- [Unités d'effort](../domain/fisheries/#effortUnits)

##### Type d’origine des données

- [Types de données](../domain/data/#types)
- [Sources de données](../domain/data/#sourcesCE)
- [Traitements de données](../domain/data/#processingsCE)

##### Couverture

- [Types d'indicateur de couverture](../domain/data/#coverageTypes)
- [Extrapolations](../domain/data/#raisings)

#### Détails du formulaire de déclaration

Formulaire [3CE](../forms/#Form_3CE)

<hr style="border:1.5px solid black">
