# Procédure de contrôle qualité {#SectionQualité}

### Métadonnées et standards des données

L'évaluation de l'adhésion des soumissions de données aux formats et aux normes établis par la CTOI est essentielle pour maintenir la cohérence et la qualité des données gérées par le Secrétariat. Il incombe aux CPC et aux autres fournisseurs de données de s'assurer que toutes les métadonnées et tous les champs de données fournis au Secrétariat sont complets et d'utiliser les listes de codes de la CTOI qui reposent sur plusieurs normes internationales et qui sont disponibles dans le [Catalogue de référence des données de la CTOI](https://data.iotc.org/reference/latest/).

Le catalogue de référence des données de la CTOI est composé de cinq domaines de données de référence :

- le [domaine administratif et géospatial](https://data.iotc.org/reference/latest/#Administrative_and_geospatial_domains) qui comprend les référentiels pour les pavillons des navires, les pays déclarant les données, les flottes de pêche, les CPC, et plusieurs couches spatiales utilisées pour soummettre des informations sur les zones de pêche ;

- [le domaine des pêcheries et des technologies de pêches](https://data.iotc.org/reference/latest/domain/fisheries) qui comprend plusieurs référentiels utilisées pour décrire les pêcheries de la CTOI, les navires, les engins de pêche et leurs configurations, ainsi que les dispositifs de pêche (par exemple, les objets flottants) et le matériel ;

- [le domaine biologique et morphométrique](https://data.iotc.org/reference/latest/domain/biological) qui comprend le référentiels des espèces de la CTOI, principalement construit à partir basé sur la liste d'espèces [ASFIS](https://data.apps.fao.org/catalog/dataset/cwp-asfis) à des fins de statistiques de la pêche, ainsi que certain référentiels utilisés pour communiquer des informations sur les méthodes d'échantillonnage et les mesures morphométriques ;

- [le domaine des données et des métadonnées](https://data.iotc.org/reference/latest/domain/data) qui regroupe les référentiels utilisés pour caractériser les éléments des jeux de données, les sources de données, les types de traitements pouvant être appliqués et les types de couverture statistique ;

- [le domaine historique et des références externes](https://data.iotc.org/reference/latest/domain/legacy) qui comprend des référentiels historiques de la CTOI et certains référentiels internationaux de la FAO, du CWP, de FIRMS, de l'IUCN et des Nations Unies.

<!-- Contact the Secretariat in case of missing value in the code list and explanation required -->

### Validation des soumissions de données

Some validators have been designed to assess the data quality based on the reporting forms.

<!-- - Check of consistency of the fields [Reporting entity](#repentity) and [flag state](#repflagstate) -->
<!-- - Grid areas must be in the [IOTC area of competence](#iotcareaofcompetence) -->
<!-- - Negative values not authorised -->
<!-- - 0 values should be converted to empty cells (NA) -->
<!-- - Effort units should be different when different units are reported -->
<!-- - Warning for gear and species aggregates -->
<!-- - Error for CE and SF in case of gear aggregate? -->
<!-- - Species aggregates not possible for the size-frequency dataset -->
<!-- - Grid areas for surface fisheries of maximum spatial resolution of 1&deg;x1&deg; -->
<!-- - Grid areas for longline fisheries of maximum spatial resolution of 5&deg;x5&deg; -->

      <!-- - Each form must be uploaded to the correspondent validator link when completed -->
      <!-- - The tool will provide an overview of the analysis carried out on the content -->
      <!-- - The output of the validation process includes a main box message with flaps of validation messages, ranging from summary information messages to increasing levels of identified issues messages provided in additional flaps. A validation-coloured summary box (left bottom), related with the level of issues message is also provided indicating if the form could be successfully processed or need further revision before to be submitted to the IOTC -->
      <!-- - When a form is fully filled, and all the mandatory data were included according to the IOTC standard an INFO message will be provided including a summary of the processed information and a validation summary message indicating that the form provided can be successfully processed and submitted to the IOTC. -->
      
      - Include list of checks for each dataset/form
    
    ### Data quality
    
    Include all checks to be made/added to each dataset (value ranges, species lists cross-checks, etc.)
    
    - The lists of species reported in the dataset ["Species presence in the catch"](#DRdataset) must be consistent with the species reported in the datasets ["Amount of fish caught and retained"](#RCdataset) and ["Amount of discards"](#DIdataset).
      
      - The list of fisheries and species reported in the dataset ["Amount of fish caught and retained"](#RCdataset) must be consistent with the fisheries and species reported in the datasets ["Geo-referenced catches and efforts"](#CEdataset) and ["Geo-referenced size frequencies"](#SFdataset).