---
title: "Directives de déclaration des données statistiques de pêche à la CTOI"
author: "Auteur: [Secrétariat de la CTOI](mailto:IOTC-Secretariat@fao.org)" 
output:
  officedown::rdocx_document:
    reference_docx: "../templates/rdoc_template_fr.docx"
  html_document2:
    css: "../templates/html_template.css"
    number_sections: FALSE
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
#       
# reference_num: TRUE
# fig_caption: TRUE
#
#csl: iotc.csl
#bibliography: WPDCS.bib
---
  
```{r general_options, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      tab.cap.pre = "Tab. ", 
                      tab.cap.sep = ". ", 
                      tab.cap.style ="Table Caption", 
                      tab.cap.fp_text = officer::fp_text_lite(italic = FALSE, bold = FALSE), 
                      fig.cap.fp_text = officer::fp_text_lite(italic = FALSE, bold = FALSE),
                      fig.cap = TRUE, 
                      fig.cap.pre = "Fig. ", 
                      fig.cap.sep = ". ", 
                      fig.cap.style = "Caption label", 
                      dpi = 150
                      )
```

```{r child = "fr/01_Objectifs.Rmd"}
```

<!-- \pagebreak -->

```{r child = "fr/02_Terminologie.Rmd"}
```

<!-- \pagebreak -->

```{r child = "fr/03_Métadonnées.Rmd"}
```

\pagebreak

```{r child = "fr/04_00_Jeux_de_Données.Rmd"}
```

\pagebreak

```{r child = "fr/05_Qualité.Rmd"}
```

<!-- \pagebreak -->

```{r child = "fr/06_Soumission.Rmd"}
```

\pagebreak

```{r child = "fr/07_01_Acronymes.Rmd"}
```

\pagebreak

```{r child = "fr/07_02_Glossaire.Rmd"}
```