---
title: "Guidelines for the reporting of fisheries statistics to the IOTC"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  officedown::rdocx_document:
    reference_docx: "../templates/rdoc_template.docx"
# output:
#   word_document2:
#     reference_docx: "../templates/doc_template.docx"
#     number_sections: FALSE
# 
  html_document2:
    css: "../templates/html_template.css"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
#       
# reference_num: TRUE
# fig_caption: TRUE
#
#csl: iotc.csl
#bibliography: WPDCS.bib
---
  
```{r general_options, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      tab.cap.pre = "Tab. ", 
                      tab.cap.sep = ". ", 
                      tab.cap.style ="Table Caption", 
#                      tab.cap.fp_text = officer::fp_text_lite(italic = TRUE, bold = TRUE), 
                      fig.cap = TRUE, 
                      fig.cap.pre = "Fig. ", 
                      fig.cap.sep = ". ", 
                      fig.cap.style = "Caption label", 
                      dpi = 150
                      )
```

```{r child = "00_01_Acronyms.Rmd"}
```

```{r child = "01_Purpose.Rmd"}
```

```{r child = "02_Terminology.Rmd"}
```

```{r child = "03_Metadata.Rmd"}
```

```{r child = "04_Dimensions.Rmd"}
```

```{r child = "05_Datasets.Rmd"}
```

```{r child = "06_Cycle.Rmd"}
```

```{r child = "07_Reference_catalogue.Rmd", eval = FALSE}
```

```{r child = "08_Validation.Rmd", eval = FALSE}
```

```{r child = "09_References.Rmd", eval = FALSE}
```

\pagebreak

```{r child = "ANNEX_1_PRIMARY_SPECIES.Rmd", eval = FALSE}
```

```{r child = "ANNEX_2_OTHER_SPECIES.Rmd", eval = FALSE}
```

```{r child = "ANNEX_3_ETP_SPECIES.Rmd", eval = FALSE}
```

\pagebreak

```{r child = "Glossary.Rmd"}
```



<!-- \pagebreak -->

<!-- ```{r child = "APPENDIX2_DOCX.Rmd"} -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r child = "APPENDIX3_DOCX.Rmd"} -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r child = "APPENDIX4_DOCX.Rmd"} -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r child = '90_DOCX.Rmd'} -->
<!-- ``` -->