# General purpose {#PurposeSection}

The collection and reporting of information on fisheries is essential for the conservation and sustainable management of tuna and tuna-like species in the Indian Ocean. Several datasets have been identified by the IOTC as instrumental in the monitoring of tuna and tuna-like fisheries and analysis of the status and trends of the populations and marine ecosystems that support them. These datasets must be reported by the [IOTC Contracting Parties and Cooperating Non-Contracting Parties](https://iotc.org/about-iotc/structure-commission) (CPCs) as part of the [IOTC Agreement](#iotcagreement) but they are also requested from any other parties that fish in the [IOTC area of competence](#iotcareaofcompetence) for species managed by the IOTC.

Since its establishment in 1996, the IOTC has developed and implemented several Conservation and Management Measures (CMMs) containing some provisions on the nature and characteristics of the data that must be reported to the IOTC. It is a national responsibility to develop and implement data recording and reporting systems that address the requirements of the IOTC defined through the [CMMs](#CMM) and the Secretariat is in charge of the collation and curation of the different datasets that support the IOTC scientific process. 

The overarching objective of the Data Reporting Guidelines (DRGs) is to provide a set of rules and best practices to the staff responsible for the collection and reporting of fisheries and biological data to the IOTC Secretariat according to the ([CMMs](#CMM)) in place. The DRGs aim to introduce the users to the IOTC specific terminology and provide a framework and standards for reporting the elements of each dataset along with some descriptive information required for storing and managing the data.

These guidelines do not include the reporting requirements related to the Regional Observer Scheme (ROS; [22/04](https://www.iotc.org/cmm/resolution-2204-regional-observer-scheme
)) as well as for the monitoring of authorised and active fishing vessels (Res. [10/08](https://www.iotc.org/cmm/resolution-1008-concerning-record-active-vessels-fishing-tunas-and-swordfish-iotc-area) and Res. [19/04](https://www.iotc.org/cmm/resolution-1904-concerning-iotc-record-vessels-authorised-operate-iotc-area-competence)), landings and transshipments of fish products in fishing ports (Res. 16/11), and transshipments at sea (Res. [23/05](https://iotc.org/cmm/resolution-2305-establishing-programme-transhipment-large-scale-fishing-vessels)) which are managed by the [compliance section of the Secretariat](https://iotc.org/compliance/reporting-templates).
