# Overview of data collection and reporting related to IOTC Resolutions 

Resolutions 15/01 and 15/02 set the standards in terms of what operational data should be collected at national level and how this must be aggregated and reported to the IOTC Secretariat.
The spatial-temporal stratification depends on the dataset, although strata generally include CPC / fleet, year, fishery, and species. Some datasets are further stratified by quarter and Indian Ocean major area (e.g., annual retained catches and annual discards) while other are stratified by month and by Indian Ocean statistical regular grids (e.g., catch-and-effort, FAD interactions, and size-frequency data), (Table1).

##Core data elements
The IOTC Resolutions define a set of requirements that are translated into a minimum set of data elements that must be included in each data set. The central data elements to be identified, collected, and included within each dataset are described as following:

###Fleet
Refers to the flag or reporting country submitting a dataset to the IOTC Secretariat.

### Data reporting entity
It generally corresponds to a country, but can also reference: the European Union (EUR) submitting data on behalf of one of its flag states;
IOTC or IPTP (Indo-Pacific Tuna Programme) when historical data was available to these two institutions only; an unknown data provider (NEI).

### Fisheries
The IOTC fishery definition combines concepts from the fishing effort domain (fishing gear, fishing ground and fishing mode) with concepts from the catch domain (target species) and in doing so can accurately describe the fishing practices of groups of vessels and be used to characterise sub-units within a fishery. 
With the IOTC Fisheries Identification Wizard, fisheries can be identified on the basis of 
(i) purpose of the fishery, (ii) area of operation, (iii) length overall category, (iv) gear category, (v) gear used to catch the fish, (vi) specific configuration of the gear used to catch the fish, (vii) fishing mode, and (viii) target species.

### Species
Refers to the species interacting with Indian Ocean fisheries as: target species (retained or discarded), non-target species (retained or discarded) and sampled individuals, including the 16 IOTC species, sharks and rays’ species of relevance to the IOTC and endangered, threatened, and protected species (ETP). The reporting of statistics by species for other species is also encouraged, especially when the catches of these species represent a significant proportion of the total catches of the fishery concerned.

As per the recommendations of the Working Parties and the Scientific Committee, the IOTC Secretariat has developed Identification Guides for marine turtles, seabirds, and sharks and rays that maybe incidentally caught or otherwise interacted with by IOTC fisheries targeting tuna and tuna-like species in the Indian Ocean. These guides are intended for use by scientific observers, field samplers, as well as fishers in order to improve the quality of the data being recorded and reported to the IOTC Secretariat. IOTC Species Identification cards and another identification resources are available on the Science section of the  IOTC website.

### Area
The IOTC Area of Competence is defined in Article 2 of the IOTC Agreement, but the spatial resolution to be used for the provision of mandatory statistical data is defined for each dataset. IOTC adopts the CWP grid classification system defined by a regular geo-referenced grid.
IOTC Resolution 15/02 states that alternative areas can be used for coastal fisheries if they better represent the fishery concerned. In general, the areas chosen should be of small size, preferably lower in size than any of the 5° grid areas located at a latitude and longitude similar to that of the area concerned. 

### Data type
Longline fleets operating in the high seas shall provide provisional data for the previous year no later than 30 June. Final data shall be submitted no later than 30 December. All other fleets (including supply vessels) shall submit their final data for the previous year no later
than 30 June.

### Data sources
Indicates where and by whom the information used to monitor fishing activities for the estimation of fisheries statistics is collected (e.g. Amounts as recorded in the vessel fishing logbook, Catch-and-effort data collected by scientific observers, Individual fish lengths /weights monitored at the landing place by staff from research institutions)

### Data processing
Refers to the type of processing or estimation method applied to raw information (e.g. Retained catches derived from catch assessment survey data, Catch-and-effort by species adjusted by using the size samples available for each trip (or alternative time-area strata), Total enumeration of individual fish lengths /weights (no estimation required).

### Data raising
Call for the level of raising applied to the data, to understand the level of representativeness that this data have with respect to the total catches and effort.

### Coverage rate
Refers to metrics used to determine the proportion that the amount of fish (number or weight) or fishing effort monitored (sampled) represents of the total (number or weight) or estimated fishing effort of each stratum for a given dataset.
