# Datasets and stratification

The type of statistical data to be submitted depends on currently standing IOTC Resolutions and varies with the fisheries and the target and bycatch species these interact with (Table 1).
Resolutions 15/01 and 15/02 set the standards in terms of what operational data should be collected at national level and how this has to be aggregated and reported to the IOTC Secretariat.
Resolution 12/02 specifies the minimum confidentiality policies to ensure that sensitive data is not publicly disseminated – unless properly aggregated – once it is received by the Secretariat.


```{r DataRequirements, tab.cap = "IOTC reference datasets and spatial-temporal resolution covered.RC-YFT Applies only to CPCs for which Res. 19/01 is still binding"}
include_Table("../inputs/data/DataRequirements.xlsx")

#IOTC cycle data reporting

•	Mandatory statistics (RC, DI, DR, CE, SF) for the year before: Jun. 30th.  (Res. 15/02 and others).
•	Daily position active buoys data (3-BU):  at least 60 days, but no longer than 90 days from the end of the month.
•	ROS Observers data:  within 150 days of completion of each trip.
•	Update of mandatory statistical data for longline fleets:  Dec 30th.

Statistical data must be submitted by e-Maris electronic reporting system for the automatic integration of data from CPCs into the IOTC Secretariat’s databases and cross-referencing obligations and reports for the specific requirements according to the provisions of the CMMs in place.
Revisions to existing datasets (for all fisheries) can be provided at any time within the limits indicated by Res. 15/02 (para. 7c).
