# IOTC fishery statistics datasets

Mandatory datasets

Total annual retained catches in live weight equivalent

Retained catch data calls for the estimated component of the catch which is retained on board during a fishing trip as total live weight of fish retained (CWP). According to Res. 15/02, CPCs must report annual retained catches by species in live weight, by quarter, main IOTC area and fishery, including the type, source and processing of the original data, as well the coverage level. 
CPCs must submit one form 1-RC for the reporting of total annual retained catches (all fisheries, data sources, species, and areas included.
CPCs for which Res. 19/01 is still binding must submit additionally the form 1RC-YFT with retained YFT catches in live weight for EEZ and ABNJ areas by gear and vessel category. <!--decommissioned-->

Total annual discarded catches
Discards are the estimated component of the catch which is the total live weight of undersized, unsaleable or otherwise undesirable whole fish and other aquatic organisms which are discarded at the time of the capture or shortly afterwards. Discarded catch refers to whole fish and other aquatic organisms discarded dead or alive and may include species taken as bycatch (CWP). Raised discard levels must be reported in live weight or numbers by species, by quarter, IO area according to Res. 15/02.
CPCs must submit one form 1-DI for the reporting of total annual discards (all fisheries, data sources, species, and areas included).

Species occurrence matrix 
Resolution 18/07 introduce the requirement of Catch reporting status trough a binary matrix by IOTC species including the most commonly caught elasmobranch species according to records of catches and incidents as established in Resolution 15/01 and main IOTC gear groups. CPCs shall complete the cells in the matrix with either a value of ‘one’ (1) to indicate where that CPC had catches (positive catch or discard) for a particular species/gear combination or a value of ‘zero’ (0) to indicate where that CPC had no catches (zero landings + zero discards) for a particular species/gear combination.
CPCs must submit one form 1-DR for the reporting of positive/zero catches by fishery type.

Interactions with ETP species
<!--To be added-->

Georeferenced catch and effort 
Fishing effort is generally defined in terms of the time spent searching for fish (search duration) and/or the amount of fishing gear of a specific type used on the fishing grounds over a given unit of time e.g. a fishing operation, fishing activity, day or fishing trip (CWP). The unit of fishing effort depends on the fishery and main gear used. The data shall be extrapolated to the total national monthly catches for each gear. Documents describing the extrapolation procedures (including raising factors corresponding to the logbook coverage) shall also be submitted routinely. Effort units reported should be consistent with those effort requirements of Resolution 15/01. 
CPCs could report catch and effort for industrial fisheries by two optional forms (3-CE and form 3-CE multiple). In the form 3- CE the metadata worksheet included information regarding data source, data processing, data raising, coverage type, effort and catch units. The use of this form implies that one form must be completed for each fishery. Form 3 – CE multiple supports the provision of data for multiple fisheries through a single form in which different values for regarding data source, data processing, data raising, coverage type, effort and catch units could be reported according to the format of the data worksheet. (Fig. 2).

CPCs must submit one form 3-CE for the reporting of annual geo-referenced catch-and-effort data, i.e., for each type of industrial fishery (all months, data sources, species, and grids included); Or One form 3-CE multiple for the reporting of annual geo-referenced catch-and-effort data, i.e., for all the industrial fisheries together (all months, data sources, species, and grids included).
For artisanal fisheries, CPCs must submit forms 3-AR for the reporting of annual geo-referenced catch-and-effort data, i.e., one for each type of coastal fishery (all months, data sources, species, and areas included).
Interactions with floating objects
The requirements for the submission of FAD data related are defined by the Resolutions 15/02, 19/02 and 23/01 resulting in four types of datasets. FOB types and activity are based on the CECOFAD  classification.

Drifting floating objects
Calls for data about the interactions with floating objects (FADs and natural objects) by purse seiners and supply vessels, including number of sets and corresponding catches by 1° grid area and month strata. CPCs must submit one form 3-FA for the reporting of annual geo-referenced FAD data, for each type of industrial surface fishery (all months, data sources species and grids included).
Support vessels information [ MOVE TO CE ]
Requires the number of support vessels and effort by 1° grid area and month strata. CPCs with active supply vessels are expected to provide one form 3-SU for the reporting of annual supply vessels’ efforts by grid area and month strata. 

Daily buoys positions 
Are the compiled monthly buoys day positions by vessel of active equipping FADs and natural floating objects for each purse seine vessel.  CPCs must submit one form 3-BU for the reporting of instrumented buoys’ position for each vessel by month. form 3-BU form is also available allowing to make one compiled monthly report for several vessels.

Anchored fish aggregating devices
Resolution 23/01 requires to all CPCs that deploy AFADs for the purpose of fishing for tuna and tuna like species under the IOTC mandate (except for recreational fisheries) to provide a monthly report of daily aFOB catches in live weights or numbers by type of aFOB, vessel, species, and location. Form 3-AA and Form 3-AA multiple are available for reporting data aFADs data to the IOTC.

Size-frequency 
Resolution 15/02 requires to the CPCs to provide Geo-referenced Individual lengths of IOTC species and the most commonly caught elasmobranch species by fishery, grid area and month strata. The Resolution also emphasize that size sampling shall be run under strict and well described random sampling schemes which are necessary to provide unbiased figures of the sizes taken. Sampling coverage shall be set to at least one fish measured by ton caught, by species and type of fishery, with samples being representative of all the periods and areas fished. 
Sampling details shall be reported in the form 4-SF where the number of sampled fish request the actual number of samples measured in that size bin for the given stratum while the number of fish will hold the number of fish estimated in the size bin from the actual number of samples. When length-frequency to catch-at-size data are not being raised and no substitution schemes are being used, the columns "No. samples" and "No. fish" must contain the same values.
CPCs may use two types of form (4-SF and form 4-SF multiple) to report size frequency data. As in the case of catch and effort, in the form 4-SF the metadata worksheet included data specifications and the use of this form implies that one form must be completed for each fishery. Form 4-SF multiple supports the provision of data for multiple fisheries and species through a single form in which different values for regarding data source, data processing, data raising, coverage type, effort and catch units could be reported according to the format of the data worksheet.
CPCs must submit one forms 4-SF for the reporting of annual geo-referenced catch-and-effort data, i.e., for each type of fishery (all months and grids included), or one form 4-SF multiple for the reporting of annual geo-referenced catch-and-effort data, i.e., for all the industrial fisheries together (all months and grids included).

Voluntary datasets

Fishing crafts
Total annual number of fishing crafts operated by type of fishery, type of craft and craft size for fisheries targeting IOTC species. 

Socio-economic data
Country indicators
<!--to be added-->

Fish prices
Average prices of fish per type of fish product (preservation, processing), weight units, type of currency, month and market.


