## Daily buoy positions {#BUdataset}

#### Description

Daily positions of operational buoys equipping DFOBs in large-scale purse seine fisheries.

#### Conservation and Management Measures
Daily positions of active buoys equipping FADs and natural floating objects for each purse seine vessel

- Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan) (para. 24) -- _Procedures on a fish aggregating devices (FADS) management plan_

#### Contents

Single daily buoy position (latitude and longitude in decimal degrees) for each of the buoys monitored by each purse seine vessel. Each buoy is identified by its unique identifier which is a concatenation of the acronym of the buoy commercial model (e.g., ISD+, M3+, T8E) followed by 5-9 digits depending on the buoy model.

#### Reporting metadata

- [Focal point full name](#fcname)
- [Focal point email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data dimensions

- Month
- Day of month
- Vessel IOTC number
- Vessel name

#### Reporting form details

Form [3BU](../forms/#Form_3BU)

<hr style="border:1.5px solid black">