## Interactions with ETP species {#INdataset}

#### Description

Annual estimates of the numbers of interactions of [longline fisheries](#iotclonglinefishery) and [surface fisheries](#iotcsurfacefishery) with endangered, threatened, and protected species by fishing fleet, fishery, IOTC main area, and species group.

#### Conservation and Management Measures

- Res. [12/04](https://iotc.org/cmm/resolution-1204-conservation-marine-turtles) -- _On the conservation of marine turtles_
- Res. [13/05](https://iotc.org/cmm/resolution-1305-conservation-whale-sharks-rhincodon-typus) -- _On the conservation of whale sharks (Rhincodon typus)_
- Res. [19/03](https://iotc.org/cmm/resolution-1903-conservation-mobulid-rays-caught-association-fisheries-iotc-area-competence) -- _On the conservation of mobulid rays caught in association with fisheries in the IOTC are fo competence_
- Res. [23/06](https://iotc.org/cmm/resolution-2306-conservation-cetaceans) -00- _On the conservation of cetaceans_
- Res. [23/07](https://iotc.org/cmm/resolution-2307-reducing-incidental-bycatch-seabirds-longline-fisheries) -- _On reducing the incidental bycatch of seabirds in longline fisheries_

#### Contents

Number of interactions with marine turtles, seabirds, mobulid rays, cetaceans and whale sharks, with information on national legislation in place in the case of cetaceans and whale sharks. For each stratum, the data coverage -- i.e., the percentage (%) of occurrences of interactions sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates.

#### Reporting metadata

- [Focal point full name](#fcname)
- [Focal point email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)


#### Data dimensions 

##### Main stratum

- [Fisheries](../domain/fisheries/#fisheries)
- [IOTC main areas](../domain/admin/#IOareasMain)
- Species group: marine turtles, seabirds, mobulid rays, cetaceans, and whale sharks

##### Original data

- [Types of data](../domain/data/#types)

##### Source coverage

- [Coverage types](../domain/data/#coverageTypes)

#### Reporting form template

Form [1IN](../forms/#Form_1IN)

<hr style="border:1.5px solid black">
