## Amount of fish caught and retained {#RCdataset}

#### Description

Total annual estimates of the amount of fish caught and retained by fishing fleet, fishery, IOTC main area, retain reason, and species.

#### Conservation and Management Measures

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) (Annex II) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and) (para. 2) -- _On mandatory statistical reporting requirements for IOTC Contracting Parties and Cooperating Non-Contracting Parties (CPCs)_
- Res. [17/05](https://www.iotc.org/cmm/resolution-1705-conservation-sharks-caught-association-fisheries-managed-iotc) (para. 6) -- _On the conservation of sharks caught in association with fisheries managed by IOTC_
- Res. [18/02](https://iotc.org/cmm/resolution-1802-management-measures-conservation-blue-shark-caught-association-iotc-fisheries) (para. 3) -- _On management measures for the conservation of blue shark caught in association with IOTC fisheries_
- Res. [18/05](https://www.iotc.org/cmm/resolution-1805-management-measures-conservation-billfishes-striped-marlin-black-marlin-blue) (para. 8) -- _On management measures for the conservation of the billfishes: striped marlin, black marlin, blue marlin and Indo-Pacific sailfish_

##### Retention bans in [longline](#iotclonglinefishery) and [surface](#iotcsurfacefishery) fisheries

- Res. [12/09](https://iotc.org/cmm/resolution-1209-conservation-thresher-sharks-family-alopiidae-caught-association-fisheries-iotc) -- _On the conservation of thresher sharks (family Alopiidae) caught in association with fisheries in the IOTC agreement area_
- Res. [13/06](https://iotc.org/cmm/resolution-1306-scientific-and-management-framework-conservation-sharks-species-caught) -- _On a scientific and management framework on the conservation of sharks in association with IOTC managed fisheries_ -- _Oceanic whitetip shark_
- Res. [19/03](https://iotc.org/cmm/resolution-1903-conservation-mobulid-rays-caught-association-fisheries-iotc-area-competence) -- _On the conservation of mobulid species caught in association with fisheries in the IOTC area of competence_

#### Contents

Estimates of retained catches in live weight equivalent (metric tonnes; t) for the IOTC species, common sharks, and other bycatch species. Reporting of quarterly estimates is voluntary and recommended to assess seasonality of the retained catches. For each stratum, the data coverage -- i.e., the percentage (%) of amount of fish sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates.

#### Reporting metadata

- [Focal point full name](#fcname)
- [Focal point email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data dimensions 

##### Main elements

- Quarter
- [Fisheries](../domain/fisheries/#fisheries)
- [IOTC main areas](../domain/admin/#IOTCareasMain)
- [Reasons for retaining](../domain/biological/#retainReasons)
- [Species](../domain/legacy/#species)

##### Original data

- [Types of data](../domain/data/#types)
- [Retained catches data sources](../domain/data/#sourcesRC)
- [Retained catches data processings](../domain/data/#processingsRC)

##### Source coverage

- [Coverage types](../domain/data/#coverageTypes)

#### Reporting form details

Form [1RC](../forms/#Form_1RC)

<hr style="border:1.5px solid black">
