## AFAD-related activities {#AAdataset}

#### Description

Daily activities conducted around [AFADs](#afad), including catches retained and discarded.

#### Conservation and Management Measures

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [23/01](https://iotc.org/cmm/resolution-2301-management-anchored-fish-aggregating-devices-afads) -- _On the management of anchored fish aggregating devices (AFADs)_

#### Contents

Geographic position and description of each fishing activity conducted around each AFAD along with estimates of retained catches and discards in numbers or live weight equivalent for the IOTC species, common sharks, and other bycatch species.

#### Reporting metadata

- [Focal point full name](#fcname)
- [Focal point email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data dimensions

##### Activity main stratum

- Month
- Day of month
- Latitude (in decimal degrees)
- Longitude (in decimal degrees)
- [Fisheries](../domain/fisheries/#fisheries)
- [AFOB types](../domain/fisheries/#FOBtypes)
- [AFOB activity types](../domain/fisheries/#FOBactivityTypes)

##### Catch main stratum

- Month
- Day of month
- Latitude (in decimal degrees)
- Longitude (in decimal degrees)
- [Fisheries](../domain/fisheries/#fisheries)
- [Species](../domain/biological/#allSpecies)
- [Types of fate](../domain/biological/#typesOfFate)
- [Catch units](../domain/fisheries/#catchUnits)

##### Source coverage

- [Raisings](../domain/data/#raisings)

#### Reporting form details

Form [3AA](../forms/#Form_3AA)

<hr style="border:1.5px solid black">