## Fishing craft statistics {#FCdataset}

#### Description

Annual number of active fishing vessels by gear, boat type, preservation and size class.

#### Conservation and Management Measures

- [UNFSA](https://www.un.org/depts/los/convention_agreements/texts/fish_stocks_agreement/CONF164_37.htm) -- _Article 4 of the Annex I of the United Nations Fish Stocks Agreement_

#### Contents

Estimates of the numbers of both [artisanal](#iotcartisanalfishingvessel) and [industrial](#iotcindustrialfishingvessel) fishing vessels involved in fishing activities during the year, stratified by boat type, mechanisation type, fish preservation method, and refrigeration storage system. For each stratum, the data coverage -- i.e., the percentage (%) of catch/effort sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates.

#### Reporting metadata

- [Focal point full name](#fcname)
- [Focal point email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data dimensions

##### Main elements

- [Fisheries](../domain/fisheries/#fisheries)
- [IOTC main areas](../domain/admin/#IOTCareasMain)
- [Boat types](../domain/fisheries/#boatTypes)
- [Mechanization types](../domain/fisheries/#mechanizationTypes)
- [Boat class types](..domain/fisheries/#boatClassTypes)
- [Fish preservation methods](../domain/fisheries/#fishPreservationMethods)
- [Fish storage types](../domain/fisheries/#fishStorageTypes)

##### Original data

- [Types of data](../domain/data/#types)
- [Fishing crafts data sources](../domain/data/#sourcesFC)
- [Fishing crafts data processings ](../domain/data/#processingsFC)

##### Source coverage

- [Coverage types](../domain/data/#coverageTypes)

#### Reporting form details

Form [2FC](../forms/#Form_2FC)

<hr style="border:1.5px solid black">
