## Species presence in the catch {#DRdataset}

#### Description

Matrix of presence of species in the retained catches or discards of each fishing fleet by gear group broken down by broad fishery category.

#### Conservation and Management Measures

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [18/07](https://www.iotc.org/cmm/resolution-1807-measures-applicable-case-non-fulfilment-reporting-obligations-iotc) -- _On measures applicable in case of non-fulfilment of reporting obligations in the IOTC_

#### Sources

[Fishing logbooks](#fishinglogbook), [fish landings](#landings), and observations-at-sea

#### Contents

Matrix table with species in rows and gear groups in columns. For each species/gear combination, the cell must be filled with either a value of 'one' (1) for some positive catch or a value of 'zero' (0) in case of absence of catch (i.e., no landing and no discard).

#### Dimensions

- Species: IOTC species, mobulid rays, common sharks, and other bycatch species   
- Gear groups: hooks and lines, pole-and-lines, longlines, purse seines, gillnets, and other gears
- Broad fishery categories: [coastal](#iotccoastalfishery) and [industrial](#iotcindustrialfishery)

#### Code lists

- [Species](../domain/biological/#allSpecies)
- [Gear groups](../domain/fisheries/#gearGroups)
- [Fishery categories](../domain/fisheries/#fisheryCategories)

#### Reporting metadata

- Focal point full name
- Focal point email
- Organisation name
- Organisation email (optional)
- Finalisation date
- Submission date
- Reporting year
- Reporting entity
- Flag state

#### Data checks

The list of species reported in the dataset must be consistent with the species reported in the retained catch or discard datasets.

#### Reporting form

Form [1DR](../forms/#Form_1DR)
