# Datasets {#DatasetSection}

## Species presence in the catch {#DR}

#### Description

Matrix of presence of species in the retained catches or discards of each fishing fleet by gear group further broken down by broad fishery category, i.e., [coastal](#iotccoastalfishery) or [industrial](#iotcindustrialfishery).

#### CMMs

Res. [18/07](https://www.iotc.org/cmm/resolution-1807-measures-applicable-case-non-fulfilment-reporting-obligations-iotc)

#### Source

[Fishing logbooks](#fishinglogbook), [fish landings](#landings), observations-at-sea

#### Contents

Matrix table with species in rows and gear groups in columns. For each species/gear combination, the cell must be filled with either a value of 'one' (1) to indicate positive catch or a value of 'zero' (0) to indicate no catch (zero landings + zero discards).

#### Scope

- Species: IOTC species, most commonly caught elasmobranch species, and other bycatch species (shortbill spearfish, other sharks, and other bony fishes).
- Gear groups: hooks and lines, pole-and-lines, longlines, purse seines, gillnets, and other gears

#### Metadata

- Focal point full name
- Focal point email
- Organisation name
- Organisation email (optional)
- Finalisation date
- Submission date
- Reporting year
- Reporting entity
- Flag state

#### Dimensions

- [Species](../domain/biological/#allSpecies)
- [Gear groups](../domain/fisheries/#gearGroups)
- [Fishery categories](../domain/fisheries/#fisheryCategories)

#### Checks

The list of species reported in the dataset must be consistent with the species reported in the retained catch or discard datasets.

#### Form

[1 DR](../forms/#Form_1DR)

\pagebreak

