
Glossary



By catch: All species, other than the 16 species listed in Annex B of the IOTC Agreement, caught or interacted with by 
fisheries for tuna and tuna-like species in the IOTC area of competence. A bycatch species includes those non-IOTC 
species which are (a) retained (byproduct), (b) incidentally taken in a fishery and returned to the sea (discarded); or (c) 
incidentally affected by interacting with fishing equipment in the fishery, but not taken

Effort. A measure of the resources used to harvest a fishery‟s stocks. The measure of effort appropriate for a fishery depends on 
the methods used and the management arrangements. Common measures include the number of vessels, the number of hooks set 
and the number of fishing days or nights.

Exclusive Economic Zone (EEZ). The area that extends from the limit of the territorial sea, which is 12 nautical miles offshore 
from the territorial sea baseline, to a maximum of 200 nautical miles, measured from the territorial sea baseline. The EEZ is less 
than 200 nautical miles in extent where it coincides with the EEZ of another country. In this case the boundaries between the two 
countries are defined by treaty.

Discard: Any part of the catch that is returned to the sea, whether dead or alive.

Fish-aggregating device (FAD). Buoys and platforms used to attract and „hold‟ pelagic fishes to enhance fishing. Can be as 
simple as a floating log or bamboo raft, but tuna fishers setting purse seine nets around tuna schools now deploy sophisticated 
FADs that allow satellite tracking and interrogation of information, such as sea surface temperature.
##CECOFAD clasifications for FAD/FOBs???###

Fork length (FL). Length of a fish measured as the distance between the tip of the snout and the point of the fork or „V‟ of the 
tail. Commonly used to record the length of commercial fish because it is little affected by damage to the tail fin (c.f. Total 
length). Fork length is measured flat, from point to point, not by stretching a tape along the body surface, which would result in a 
longer measurement for full-bodied fish like tuna. See also Lower-jaw fork length.

### GEAR TYPES check ISSCFG descirption/codes####


Retained catches ## check cwp/? definitions??##

