# Glossary

**A**

**Anchored Fish Aggregating Device (AFAD)**. A fish aggregating device tethered to the bottom of the ocean. It usually consists of a very large buoy and it is anchored to the bottom of the ocean with a chain. Cf. Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan).

**Archival tag (data storage tag)**. Implanted fish tag that detects and records (‘archives’) environmental variables (e.g., water temperature) and location over time.

**Artisanal fishery**. Traditional fishery that involves fishing households (as opposed to commercial companies), using relatively small amounts of capital and energy, relatively small fishing vessels (if any), making short fishing trips close to shore, mainly for local consumption. In practice, definition varies between countries, e.g., from gleaning or a one-man canoe in poor developing countries, to more than 20 m trawlers, seiners, or longliners in developed ones. Artisanal fisheries can be subsistence or commercial fisheries, providing for local consumption or export. They are sometimes referred to as small-scale fisheries ([FAO 2005](https://www.fao.org/documents/card/en/c/ae76ef51-be20-5e71-aec5-b469e5e0a673)).

**Artisanal fishery (IOTC)**. Fishery composed of fishing vessels of less than 24 m length overall that exclusively operate in the exclusive economic zone of their flag state, i.e., not recorded in the IOTC Record of Authorised Vessels. Equivalent to coastal fisheries. Cf. Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and).

**Associated school**. The fish school is associated with a topographic structure (e.g., seamount), an anchored or a drifting floating object, including man-made rafts such as fish aggregating devices and live animals in motion (e.g., whale sharks, cetaceans).

**B**

**Bycatch**. Discarded catch plus incidental catch ([Alverson et al. 1994](https://www.fao.org/3/t4890e/T4890E00.htm)).

<!-- By catch: All species, other than the 16 species listed in Annex B of the IOTC Agreement, caught or interacted with by  -->
<!-- fisheries for tuna and tuna-like species in the IOTC area of competence. A bycatch species includes those non-IOTC  -->
<!-- species which are (a) retained (byproduct), (b) incidentally taken in a fishery and returned to the sea (discarded); or (c)  -->
<!-- incidentally affected by interacting with fishing equipment in the fishery, but not taken -->

<!-- Effort. A measure of the resources used to harvest a fishery‟s stocks. The measure of effort appropriate for a fishery depends on  -->
<!-- the methods used and the management arrangements. Common measures include the number of vessels, the number of hooks set  -->
<!-- and the number of fishing days or nights. -->

<!-- Exclusive Economic Zone (EEZ). The area that extends from the limit of the territorial sea, which is 12 nautical miles offshore  -->
<!-- from the territorial sea baseline, to a maximum of 200 nautical miles, measured from the territorial sea baseline. The EEZ is less  -->
<!-- than 200 nautical miles in extent where it coincides with the EEZ of another country. In this case the boundaries between the two  -->
<!-- countries are defined by treaty. -->

<!-- Discard: Any part of the catch that is returned to the sea, whether dead or alive. -->

<!-- Fish-aggregating device (FAD). Buoys and platforms used to attract and „hold‟ pelagic fishes to enhance fishing. Can be as  -->
<!-- simple as a floating log or bamboo raft, but tuna fishers setting purse seine nets around tuna schools now deploy sophisticated  -->
<!-- FADs that allow satellite tracking and interrogation of information, such as sea surface temperature. -->
<!-- ##CECOFAD clasifications for FAD/FOBs???### -->

<!-- Fork length (FL). Length of a fish measured as the distance between the tip of the snout and the point of the fork or „V‟ of the  -->
<!-- tail. Commonly used to record the length of commercial fish because it is little affected by damage to the tail fin (c.f. Total  -->
<!-- length). Fork length is measured flat, from point to point, not by stretching a tape along the body surface, which would result in a  -->
<!-- longer measurement for full-bodied fish like tuna. See also Lower-jaw fork length. -->

<!-- ### GEAR TYPES check ISSCFG descirption/codes#### -->


<!-- Retained catches ## check cwp/? definitions??## -->

