# Glossary

#### A

**Anchored Fish Aggregating Device (AFAD)**. A fish aggregating device tethered to the bottom of the ocean. It usually consists of a very large buoy and it is anchored to the bottom of the ocean with a chain. Cf. Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan).

**Archival tag (data storage tag)**. Implanted fish tag that detects and records (‘archives’) environmental variables (e.g., water temperature) and location over time.

**Artisanal fishery**. Traditional fishery that involves fishing households (as opposed to commercial companies), using relatively small amounts of capital and energy, relatively small fishing vessels (if any), making short fishing trips close to shore, mainly for local consumption. In practice, definition varies between countries, e.g., from gleaning or a one-man canoe in poor developing countries, to more than 20 m trawlers, seiners, or longliners in developed ones. Artisanal fisheries can be subsistence or commercial fisheries, providing for local consumption or export. They are sometimes referred to as small-scale fisheries ([FAO 2005](https://www.fao.org/documents/card/en/c/ae76ef51-be20-5e71-aec5-b469e5e0a673)).

**Artisanal fishery (IOTC)**. Fishery composed of fishing vessels of less than 24 m length overall that exclusively operate in the exclusive economic zone of their flag state, i.e., not recorded in the IOTC Record of Authorised Vessels. Equivalent to coastal fisheries. Cf. Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and).

**Associated school**. The fish school is associated with a topographic structure (e.g., seamount), an anchored or a drifting floating object, including man-made rafts such as fish aggregating devices and live animals in motion (e.g., whale sharks, cetaceans).

#### B

**Bycatch**. Discarded catch plus incidental catch ([Alverson et al. 1994](https://www.fao.org/3/t4890e/T4890E00.htm)).

**Bycatch species (IOTC)**. All species, other than the 16 species listed in Annex B of the IOTC Agreement, caught or interacted with by fisheries for tuna and tuna-like species in the IOTC area of competence. A bycatch species includes those non-IOTC species which are (a) retained (byproduct), (b) incidentally taken in a fishery and returned to the sea (discarded); or (c) incidentally affected by interacting with fishing equipment in the fishery, but not taken.

**Byproduct**. A species taken incidentally in a fishery while fishing for the target species that has some commercial value and is retained for sale.

#### C {#C}

**Coastal fishery (IOTC)**. Fishery composed of fishing vessels of less than 24 m length overall that exclusively operate in the exclusive economic zone of their flag state, i.e., not recorded in the IOTC Record of Authorised Vessels. Equivalent to IOTC artisanal fishery. Cf. Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and).

**Conservation and Management Measure**. Any measure adopted pursuant to Articles V(2)(c) and IX in the IOTC Agreement, and more generally where not applicable to IOTC such measures that are consistent with international law.

**Coordinating working party on Fishery Statistics (CWP)**. International and interorganizational forum for agreeing common definitions, classifications and standards for the collection of fishery and aquaculture statistics. It has developed common procedures for statistics collation which have streamlined processes and reduced the burden on the statistical offices of national fisheries and aquaculture production, as well as providing technical advice to participating organisations on fishery-related and aquaculture-related statistical matters, and facilitating the publication of methodological and reference documents ([https://www.fao.org/cwp-on-fishery-statistics/background/en/](https://www.fao.org/cwp-on-fishery-statistics/background/en/)).

#### D

**Discards**. All non-retained catch, including individuals released alive or discarded dead ([Alverson et al. 1994](https://www.fao.org/3/t4890e/T4890E00.htm)).

**Drifting fish aggregating device (DFAD)**. Fish aggregating device not tethered to the bottom of the ocean typically composed of a floating structure (such as a bamboo or metal raft with buoyancy provided by buoys, corks, etc.) and of a submerged structure (made of canvass, ropes, etc.).

**Driftnet (drift gillnet)**. A drift gillnet is a type of gillnet that is not fixed to the seabed but allowed to drift with the current ([https://www.fao.org/fishery/en/geartype/220/en](https://www.fao.org/fishery/en/geartype/220/en)).

#### E

**Elasmobranchs**. Subclass of chondrichthyes or cartilaginous fish, including modern sharks (superorder Selachii), skates, rays, and sawfish (superorder Batoidea) ([Wikipedia](https://en.wikipedia.org/wiki/Elasmobranchii)).

**Engine power**. Power that an engine can put out, generally expressed in kilowatt (kw) or horsepower (hp).

**Exclusive economic zone (EEZ)**. An area beyond and adjacent to the territorial sea, subject to the specific legal regime established in the United Nations Convention on the Law of the Sea, which provides that it is not to extend beyond 200 nm from the baselines from which the breadth of the territorial sea is measured.

#### F

**Fish aggregating device (FAD)**. A permanent, semi-permanent or temporary object, structure or device of any material, man-made or natural, which is deployed and/or tracked, for the purpose of aggregating target tuna species for consequent capture. Cf. Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan).

**Fisher**. An individual who engages in fishing activities for the purpose of deriving a livelihood, generating a revenue or pursuing sport or recreation. A full-time, part-time or occasional fisher receives some or all of their livelihood from fishing or spends some or all of their working time in that occupation. A sport or recreational fisher (or angler) conducts fishing in pursuit of sport or recreation (CWP).

**Fishery vessel**. Mobile floating platform of any kind and size, operating in fresh, brackish or marine waters which are used for catching, harvesting, searching, transporting, landing, preserving and/or processing fish, shellfish and other aquatic organisms, residues and plants ([CWP](https://www.fao.org/cwp-on-fishery-statistics/handbook/capture-fisheries-statistics/fishery-fleet/en/)).

**Fishing capacity**. The ability of a vessel or fleet of vessels to catch fish. Fishing capacity (capacity output) can be expressed more specifically as the maximum amount of fish over a period of time (year, season) that can be produced by a fishing fleet if fully utilised, given the biomass and age structure of the fish stock and the present state of the technology ([Pascoe and Greboval 2003](https://www.fao.org/3/Y4849E/y4849e00.htm)).

**Fishing effort (effective)**. Adjusted measure of effort to take account of differences in fishing power and efficiency and ensure proportionality with fishing mortality, and when two or more kinds of gear are used or when the same gear is used for example by different classes of vessel or métier, the respective efforts are adjusted to some common standard before being aggregated across all classes (strata) (CWP).

**Fishing effort (nominal)**. General measure of effort used to quantify the unadjusted, total effort units exerted on a stock in a given time period by a fishery, gear or métier (CWP).

**Fishing logbook**. A permanently bound logbook issued by the flag State of a vessel and required for any purpose relating to fishing or related activities, with irremovable pages, each of which is consecutively numbered and printed with an applicable serial number and/or an electronic logbook, being computerised record of information and data relating to fishing or related activities in such template as may be required,
including under any conservation and management measure.

**Fishing mode**. A specific practice or method of conducting a fishing operation or searching for fish within a fishery, fishing sector or region. A fishing mode may also be associated with a métier (CWP).

**Fishing power**. Effectiveness of a vessel’s fishing effort relative to the effectiveness of other vessels.

**Fishing vessel**. Fishery vessel only engaged in catching operations. The term “non-fishing vessel” applies to vessels performing other functions related to fisheries; this includes vessels providing supplies, motherships, fish carriers, and vessels involved in fisheries resources protection, aquaculture operations, and vessels rendering assistance or conducting fisheries related research or training ([Thermes et al. 2003](https://www.fao.org/fishery/en/publications/278529)).

**Flag state**. The State in which a vessel is registered, providing it is only registered in one State.

**Fork length (FL)**. Length of a fish measured as the straight distance between the tip of the snout and the point of the fork or ‘V’ of the tail.

<!-- Commonly used to record the length of commercial fish because it is little affected by damage to the tail fin. Fork length is measured flat, from point to point, not by stretching a tape along the body surface, which would result in a longer measurement for full-bodied fish like tuna. -->

**Free school**. The fish school is not associated with any anchored or drifting floating object. Equivalent to free-swimming school or unassociated.

#### G

**Gear**. The general name for the equipment used for fishing. This might include lines, nets, warps, floats, deck equipment and any other specific fishing items ([Thermes et al. 2023](https://www.fao.org/fishery/en/publications/278529)).

**Gillnet**. Type of passive fishing gear consisting of panels of net held vertically in the water column, either in contact with the seabed or suspended from the sea surface, such that fish attempting to swim through the net are entangled. The mesh size of the net determines the size range of fish caught, as smaller fish can swim through the meshes and larger fish are not enmeshed ([https://www.fish.wa.gov.au/](https://www.fish.wa.gov.au/)).

**Gross tonnage (GT)**. Dimensionless measure of the overall size of a ship ([Thermes et al. 2023](https://www.fao.org/fishery/en/publications/278529)).

#### H

**Handline (handlining**. Fishing method in which a line with a hook, usually baited, is lowered into the water from a drifting, anchored or moving fishing vessel or from a jetty, pier or rock on the shore overlooking the water ([Bjarnason 1992](https://www.fao.org/3/t0511e/T0511E00.htm)).

**High-seas**. All parts of the sea that are not included in the exclusive economic zone, in the territorial sea or in the internal waters of a State, or in the archipelagic waters of an archipelagic State ([UNCLOS](https://en.wikisource.org/wiki/United_Nations_Convention_on_the_Law_of_the_Sea)).

#### I

**Industrial fishery**. Fishery that (i) catches fish from large and medium-sized vessels fitted out with mechanised methods of operating the fishing gear and installations for preservation of fish on board, (ii) process the catch either in land base or on board – in which cases the vessels are provided with appropriate processing installations, and (iii) distribute the fish products around the country and abroad using mechanised means of transportation adapted for fish and fish products. All these activities are generally organised for the financial benefit of the companies or organisations operating the fishing vessels, processing plants, and fish product transportation ([Thermes et al. 2023]((https://www.fao.org/fishery/en/publications/278529)).

**Industrial fishery (IOTC)**. Fishery composed of industrial fishing vessels following the IOTC definition.

**Industrial fishing vessel**. Large vessel, typically of 24 m in length and over, engaged in catching operations, outfitted with mechanised methods of operating the fishing gear and installations for preservation of fish on board ([Thermes et al. 2023](https://www.fao.org/fishery/en/publications/278529)).

**Industrial fishing vessel (IOTC)**. Vessel recorded in the IOTC Record of Authorised Vessels, i.e., of 24 m length overall and over, or of less than 24 m length overall that operates in waters outside the Economic Exclusive Zone of her flag State. Cf. Res. 19/04.

**IOTC active vessel list**. The list of vessels having operated in the IOTC area of competence in a given year, including fishing and non-fishing vessels of 24 m length overall and over, or of less than 24 m length overall that operated in waters outside the economic exclusive zone of the flag State. Cf. Res. [10/08](https://www.iotc.org/cmm/resolution-1008-concerning-record-active-vessels-fishing-tunas-and-swordfish-iotc-area).

**IOTC Agreement**. The 1993 Agreement for the establishment of the Indian Ocean Tuna Commission.

**IOTC area of competence**. The Indian Ocean (defined for the purpose of the IOTC Agreement as being FAO Statistical Areas 51 and 57), and adjacent seas, north of the Antarctic Convergence, insofar as it is necessary to cover such seas for the purpose of conserving and managing stocks that migrate into or out of the Indian Ocean. In 1999, the Commission extended the western boundary of the IOTC statistical area from 30ºE to 20ºE, thus eliminating the gap in between the areas covered by the IOTC and ICCAT. Cf. [https://www.fao.org/fishery/en/organization/iotc](https://www.fao.org/fishery/en/organization/iotc.

**IOTC fishery categories**. TO DO

**IOTC record of authorised vessels**. The list of vessels authorised to operate in the IOTC Area of Competence in a given time period, including fishing and non-fishing vessels of 24 m length overall and over, or of less than 24 m length overall that may operate in waters outside the economic exclusive zone of the flag State. These vessels are referred to as authorised fishing vessels (AFVs). Cf. Res. [19/04](https://www.iotc.org/cmm/resolution-1904-concerning-iotc-record-vessels-authorised-operate-iotc-area-competence).

**IOTC species**. Any or all of the 16 tuna and tuna-like species listed in Annex B of the IOTC Agreement.
Instrumented buoy. A buoy with a clearly marked with a unique reference number allowing identification of its owner and equipped with a satellite tracking system to monitor its position. Cf. Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan).








