# Data submission semantics

The new  data reporting forms are designed to accommodate for the reporting of complete annual datasets of a given type, stratified by the relevant criteria.
This means that at each annual submission from a CPC, the Secretariat expects to receive:
  •	One Form 1-RC interim for the reporting of total annual retained catches (all fisheries, data sources, species, and areas)
•	One Form 1-DI interim for the reporting of total annual discards (all fisheries, data sources, species, and areas)
•	One Form 1-DR for the reporting of zero catches by fishery type (all fisheries and species)
•	One Form 2-FC interim for the voluntary reporting of fishing craft statistics (all fisheries, data sources and boat types)
•	One Form 3-CE interim (multiple) for the reporting of annual geo-referenced catch-and-effort data (all fisheries, months, data sources, species, and grids)
•	One Form 4-SF interim (multiple) for the reporting of individual body lengths or weights data (all fisheries, months, data sources, species, measurement types, and grids)
•	One or more Form 3-BU (multiple) for the reporting of instrumented buoys’ position, i.e., one for each month (all vessels)
•	One or more form 3-DA (multiple) for the reporting of interactions between vessels and dFOBs, i.e., one for each month (all vessels)
The semantics of the data submission process are defined as follows:
  a)	CPCs should submit by the deadline one form for each data set, and each of these forms shall contain information for all fisheries and species for a given reference year, except for Form 3-BU, 3-DA, and 3-AA (if endorsed) which might require multiple submissions due to their different spatio-temporal resolution
b)	Any subsequent resubmission of forms 1-RC interim, 1-DI interim, 1-DR, 2-FC interim, 3-CE ¬interim (multiple), 4-SF interim (multiple) is considered as a full replacement of the annual information for that given dataset as originally provided in a)
c)	The use of the single versions of form 3-CE interim, 3-BU, and 4-SF interim is endorsed only for the provision of updates of already submitted annual data in a) or b) for a single fishery (3-CE), species (4-SF), or vessel (3-BU).

