## Fish prices {#PRdataset}

#### Description

Monthly prices of fish products for tuna and tuna-like species under IOTC mandate.

#### Conservation and Management Measures

- [IOTC Agreement](#iotcAgreement) (paras. 1 and 2d) -- _Article V. Objectives, functions and responsibilities of the Commission_

#### Contents

Monthly average prices of fish per type of fish product -- i.e., processing type,  by weight category, and market.

currency, 

#### Reporting Metadata

- [Liaison officer full name](#fcname)
- [Liaison officer email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data Dimensions

##### Main Elements

- Month
- Currency
- Destination
- Market
- [IOTC Species](../../domain/biology/index.html#IOTC_Species)
- [Fish processing types](../../domain/fisheries/index.html#fishProcessingTypes)
- [Fish preservation methods](../../domain/fisheries/index.html#fishPreservationMethods)
- Weight class (lo)
- Weight class (hi)

#### Reporting Form Details

Form [7PR](../../forms/index.html#Form_7PR)

<hr style="border:1.5px solid black">
