## Fishing Craft Statistics {#FCdataset}

#### Description

Annual number of active fishing vessels by vessel type, gear, and main technical features.

#### Conservation and Management Measures

- [UNFSA](https://www.un.org/depts/los/convention_agreements/texts/fish_stocks_agreement/CONF164_37.htm) -- _Article 4 of the Annex I of the United Nations Fish Stocks Agreement_

#### Contents

Estimates of the numbers of fishery vessels active during the year, stratified by type of vessel, architecture, mechanisation, fish preservation method, and refrigeration storage system. For each stratum, the data coverage -- i.e., the percentage (%) of catch/effort sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates.

#### Reporting Metadata

- [Liaison officer full name](#fcname)
- [Liaison officer email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data Dimensions

##### Main Elements

- [Vessel types](../../domain/fisheries/index.html#vesselTypes)
- [Vessel architectures](../../domain/fisheries/index.html#vesselArchitectures)
- [Mechanisation types](../../domain/fisheries/index.html#mechanisationTypes)
- [Vessel size class types](../../domain/fisheries/index.html#vesselSizeTypes)
- [Fish preservation methods](../../domain/fisheries/index.html#fishPreservationMethods)
- [Fish storage types](../../domain/fisheries/index.html#fishStorageTypes)

##### Original Data

- [Types of data](../../domain/data/index.html#types)
- [Data sources](../../domain/data/index.html#sourcesFC)
- [Data processings ](../../domain/data/index.html#processingsFC)

##### Source Coverage

- [Coverage types](../../domain/data/index.html#coverageTypes)

#### Reporting Form Details

Form [2FC](../../forms/index.html#Form_2FC)

<hr style="border:1.5px solid black">
