# Data reference catalogue 

Several standard and IOTC-specific code lists are used in the IOTC forms for reporting statistical data. IOTC forms are complemented by a catalogue of reference data categorized by their functional domain including a collection of codelists modelling the followings:

Administrative and geospatial: vessel flags and / or data reporting countries, fishing fleets, IOTC CPCs, geospatial data for irregular areas and / or regular grids of relevance to the IOTC.
Fisheries and fishing technologies: all IOTC fisheries and their configuration elements, fishing trip details (ROS), vessel characteristics and technologies (ROS), gear characteristics, fishing activities, FAD-related classifications, bycatch mitigation measures and devices and transhipments data.
Biological and morphometric: species details and categorizations, tagging details, sampling details, morphometric data. 
Data and metadata: characterizing elements of core statistical datasets (type of data, data raising, and estimation), all types of data sources and data processing (dataset-specific), original data coverage. 
Legacy and external data references domains: FAO reference codes (CWP-ISSCFG, FIRMS-GRSF, NOCS) IUCN reference codes, UN reference codes (UN/LOCODE port codes)

Each code list is preceded by a short description and references to the IOTC data reporting forms on which the code list is referenced, and includes an alphabetical code, an English and French name, and relevant information according to each data domain. The reference data catalogue allows codelists to be filtered and ordered by field and downloaded as a CSV file for offline reference. 

