
# SPECIES ####

## Primary species ####
PRIMARY_SPECIES = query(C_MASTER, "SELECT CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES_IOTC WHERE IS_AGGREGATE = 0 ORDER BY 1")

PRIMARY_SPECIES[, SPECIES_CODE := factor(SPECIES_CODE)]

## Other species ####
OTHER_SPECIES = fread("../inputs/data/OTHER_SPECIES_GG_RES1501.csv")
  
# 'MZZ', 'SRX', 

## ETP species #####

### Whale sharks ####
WHALE_SHARK = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE CODE LIKE 'RHN'")

### Turtles ####
TURTLE_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'TURTLES' AND IS_AGGREGATE = 'false'")

### Cetaceans ####
CETACEAN_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'CETACEANS' AND IS_AGGREGATE = 'false'")

### Seabirds ####
SEABIRD_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'SEABIRDS' AND IS_AGGREGATE = 'false'")

ETP_SPECIES = rbindlist(list(WHALE_SHARK, TURTLE_SPECIES, CETACEAN_SPECIES, SEABIRD_SPECIES))

