print("Extracting code lists...")


# SPECIES ####

## Primary species ####

### English ####
PRIMARY_SPECIES = query(C_MASTER, "SELECT CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES_IOTC WHERE IS_AGGREGATE = 0 ORDER BY 1")

PRIMARY_SPECIES[, SPECIES_CODE := factor(SPECIES_CODE)]

### French ####
ESPECES_PRIMAIRES = query(C_MASTER, "SELECT CODE AS CODE_ESPECE, NAME_FR AS ESPECE, NAME_SCIENTIFIC AS ESPECE_SCIENTIFIQUE FROM refs_biological.V_SPECIES_IOTC WHERE IS_AGGREGATE = 0 ORDER BY 1")

ESPECES_PRIMAIRES[, CODE_ESPECE := factor(CODE_ESPECE)]

## Other species ####

### English ####
OTHER_SPECIES = fread("../inputs/data/OTHER_SPECIES_GG_RES1501.csv")[, .(GEAR_GROUP, SPECIES_CODE, SPECIES = NAME_EN, SPECIES_SCIENTIFIC)]

### French ####
ESPECES_AUTRES = fread("../inputs/data/OTHER_SPECIES_GG_RES1501.csv", encoding = "UTF-8")[, .(GROUPE_ENGINS = GEAR_GROUP_FR, CODE_ESPECE = SPECIES_CODE, ESPECE = NAME_FR, ESPECE_SCIENTIFIQUE = SPECIES_SCIENTIFIC)]

## ETP species #####

### English ####
ETP_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE AS SPECIES_CODE, NAME_EN AS SPECIES, NAME_SCIENTIFIC AS SPECIES_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE (IS_AGGREGATE = 'false' AND ((CODE LIKE 'RHN') OR (SPECIES_CATEGORY_CODE IN ('TURTLES', 'CETACEANS', 'SEABIRDS'))))")

ETP_SPECIES[, SPECIES_CATEGORY_CODE := str_to_title(tolower(SPECIES_CATEGORY_CODE))]

### French ####
ESPECES_ETP = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE AS CODE_CATEGORIE_ESPECES, [ORDER] AS ORDRE, CODE AS CODE_ESPECE, NAME_FR AS ESPECE, NAME_SCIENTIFIC AS ESPECE_SCIENTIFIQUE FROM refs_biological.V_SPECIES WHERE (IS_AGGREGATE = 'false' AND ((CODE LIKE 'RHN') OR (SPECIES_CATEGORY_CODE IN ('TURTLES', 'CETACEANS', 'SEABIRDS'))))")

ESPECES_ETP[, CODE_CATEGORIE_ESPECES := str_to_title(tolower(CODE_CATEGORIE_ESPECES))]
