
# SPECIES ####

## Primary species ####
PRIMARY_SPECIES = query(C_MASTER, "SELECT CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES_IOTC WHERE IS_AGGREGATE = 0 ORDER BY 1")

PRIMARY_SPECIES[, CODE := factor(CODE)]

## Other species ####
OTHER_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE CODE IN ('SMA', 'LMA', 'SPK', 'SPL', 'SPZ', 'PTH', 'BTH', 'ALV', 'BSH', 'FAL', 'OCS', 'POR', 'TIG', 'PSK', 'WSH', 'RMA', 'RMB', 'RME', 'RMK', 'RMM', 'RMT', 'RMO', 'PLS', 'SSP') ORDER BY 1, 2")
  
# 'MZZ', 'SRX', 

## ETP species #####

### Whale sharks ####
WHALE_SHARK = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE CODE LIKE 'RHN'")

### Turtles ####
TURTLE_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'TURTLES' AND IS_AGGREGATE = 'false'")

### Cetaceans ####
CETACEAN_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'CETACEANS' AND IS_AGGREGATE = 'false'")

### Seabirds ####
SEABIRD_SPECIES = query(C_MASTER, "SELECT SPECIES_CATEGORY_CODE, [ORDER], CODE, NAME_EN, NAME_SCIENTIFIC FROM refs_biological.V_SPECIES WHERE SPECIES_CATEGORY_CODE = 'SEABIRDS' AND IS_AGGREGATE = 'false'")

ETP_SPECIES = rbindlist(list(WHALE_SHARK, TURTLE_SPECIES, CETACEAN_SPECIES, SEABIRD_SPECIES))

