# General purposes {#PurposeSection}

Effective collection and reporting of fisheries data are essential for conserving and sustainably managing tuna and tuna-like species in the Indian Ocean. The Indian Ocean Tuna Commission (IOTC) has identified several datasets critical for monitoring tuna and tuna-like fisheries and analysing the status and trends of both the populations and the marine ecosystems that support them. These datasets must be reported by the [IOTC Contracting Parties and Cooperating Non-Contracting Parties](https://iotc.org/about-iotc/structure-commission) (CPCs) as part of the [IOTC Agreement](#iotcagreement) but they are also requested from any other Parties that fish in the [IOTC Area of Competence](#iotcareaofcompetence) for species managed by the IOTC.

Since its establishment in 1996, the IOTC has developed and implemented several Conservation and Management Measures (CMMs) which include specific provisions on the nature and characteristics of the data that must be collected and reported to the IOTC Secretariat. It is the responsibility of each country to establish and enforce data recording and reporting systems that meet the criteria set by the IOTC through its [CMMs](#cmm) and the Secretariat oversees the collation and curation of the different datasets that support the IOTC scientific process.

The overarching objective of the Data Reporting Guidelines (DRGs) is to provide a set of rules and best practices to the staff responsible for the collection and reporting of fisheries and biological data to the IOTC Secretariat according to the [CMMs](#cmm) in place. The DRGs aim to:

1. Introduce the users to the IOTC terminology (section [Terminology](#TerminologySection))
2. Provide the framework and standards for reporting the elements of the data along with the metadata information required for their storage and management (section [Metadata](#MetadataSection))
3. Describe the contents of each dataset as included in the mandatory IOTC reporting forms (section [Datasets](#DatasetSection)), 
4. Present the IOTC data quality control procedure and detail the checks to be performed on the metadata and data prior to any submission (section [Quality control procedure](#QualitySection))
5. Explain the main features of the submission process, including details on the data submission platform, reporting timeline, structure of the files to be reported, and procedure for revising historical submissions (section [Data submission procedure](#SubmissionSection)).

These guidelines do not include the reporting requirements related to the Regional Observer Scheme (ROS; [22/04](https://www.iotc.org/cmm/resolution-2204-regional-observer-scheme
)) as well as to the monitoring of authorised and active fishing vessels (Res. [10/08](https://www.iotc.org/cmm/resolution-1008-concerning-record-active-vessels-fishing-tunas-and-swordfish-iotc-area) and Res. [19/04](https://www.iotc.org/cmm/resolution-1904-concerning-iotc-record-vessels-authorised-operate-iotc-area-competence)), landings and transhipments of fish products in fishing ports ([Res. 16/11](https://www.iotc.org/cmm/resolution-1611-port-state-measures-prevent-deter-and-eliminate-illegal-unreported-and)), and transhipments at sea (Res. [23/05](https://iotc.org/cmm/resolution-2305-establishing-programme-transhipment-large-scale-fishing-vessels)) which are managed by the [compliance section](https://iotc.org/compliance/reporting-templates) of the Secretariat.