## DFOB-related activities {#DAdataset}

#### Description

Operational activities conducted by purse seine and support vessels on drifting floating objects (DFOBs) and buoys.

#### Conservation and Management Measures

- Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and) (para. 6c) -- _On mandatory statistical reporting requirements for IOTC Contracting Parties and Cooperating Non-Contracting Parties (CPCs)_
- Res. [19/02](https://iotc.org/cmm/resolution-1902-procedures-fish-aggregating-devices-fads-management-plan) (para. 11 and Annex III) -- _Procedures on a fish aggregating devices (FADs) management plan_ (binding for Oman)
- Res. [24/02](https://iotc.org/cmm/resolution-2402-management-drifting-fish-aggregating-devices-fads-iotc-area-competence) (para. 45 and Annex I) -- _On management of drifting fish aggregating devices (FADs) in the IOTC area of competence_

#### Contents

When present, information on buoy identifier, knowledge of the buoy position, and type of activity conducted on the buoy. For each DFOB, information on materials (i.e., presence of plastic or metal), dimensions (i.e., length, width, and height), and presence of mesh with value of mesh size for both the surface (i.e., raft) and subsurface (i.e., tail) components. Finally, species-specific estimates of catches retained and discarded in numbers or live weight equivalent for the IOTC species, common sharks, and other bycatch species.

#### Reporting metadata

- [Liaison officer full name](#fcname)
- [Liaison officer email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data dimensions

##### Buoy and DFOB main stratum

- Vessel IOTC number
- Vessel name
- Month
- Day of month
- UTC time
- Latitude (in decimal degrees)
- Longitude (in decimal degrees)

##### Catch main stratum

- Vessel IOTC number
- Vessel name
- Month
- Day of month
- UTC time
- Latitude (in decimal degrees)
- Longitude (in decimal degrees)
- [Species](../domain/biology/#allSpecies)
- [Types of fate](../domain/biology/#typesOfFate)
- [Catch units](../domain/fisheries/#catchUnits)

#### Reporting form details

Form [3DA](../forms/#Form_3DA)

<hr style="border:1.5px solid black">
