## Geo-referenced size frequencies {#SFdataset}

#### Description

Monthly estimates of size frequencies of the catch retained and discarded by fishing fleet, fishery, grid area of 5&deg; longitude and latitude, species, and sex for IOTC species, common sharks, and other bycatch species.

#### Conservation and Management Measures

-   Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) (Annex II) -- *On the recording of catch and effort data by fishing vessels in the IOTC area of competence*
-   Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and) (para. 5) -- *On mandatory statistical reporting requirements for IOTC Contracting Parties and Cooperating Non-Contracting Parties (CPCs)*
-   Res. [17/05](https://www.iotc.org/cmm/resolution-1705-conservation-sharks-caught-association-fisheries-managed-iotc) (para. 6) -- *On the conservation of sharks caught in association with fisheries managed by IOTC*
-   Res. [18/02](https://iotc.org/cmm/resolution-1802-management-measures-conservation-blue-shark-caught-association-iotc-fisheries) (para. 3) -- *On management measures for the conservation of blue shark caught in association with IOTC fisheries*
-   Res. [18/05](https://www.iotc.org/cmm/resolution-1805-management-measures-conservation-billfishes-striped-marlin-black-marlin-blue) (para. 8) -- *On management measures for the conservation of the billfishes: striped marlin, black marlin, blue marlin and Indo-Pacific sailfish*

#### Reporting metadata

-   [Liaison officer full name](#fcname)
-   [Liaison officer email](#fcemail)
-   [Organisation name](#orgname)
-   [Organisation email](#orgemail)
-   [Finalisation date](#findate)
-   [Submission date](#subdate)
-   [Reporting year](#repyear)
-   [Reporting entity](#repentity)
-   [Flag state](#repflagstate)

#### Contents

Size frequencies correspond to the numbers of individuals in a catch or catch sample within each size interval ([UN ESCWA](https://www.unescwa.org/sd-glossary/length-frequency-distribution-lfd)). Straight length measurements made using a calliper or measuring board are recommended over fish weights and vary according to fish groups: (i) [lower-jaw fork length](#lj) for billfish, (ii) [upper-jaw fork length](#fl) for tunas, mackerels, sharks, and all other bycatch fish species with forked or lunate tails, (iii) [standard length](#sl) for bycatch fish species with rounded or truncate tails, and (iv) [disc width](#dw) for rays. The Secretariat further recommends the use of length intervals for the IOTC species and most commonly caught sharks, along with maximum length intervals and ranges of valid values, which are used to filter and consolidate the size-frequency datasets made available to support the IOTC process (see [Recommended measurements](../domain/biology/#morphometricsRecommended)).

Size-frequency data must be collected for the 16 [IOTC species](#iotcspecies) and the most commonly caught elasmobranch species listed in IOTC [Res. 15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) for taxa identified at species level. 

Size data can be collected either at sea or on land and must be linked to the spatial origin of the catch. Data should be reported following a spatial resolution of [5° grid areas](https://data.iotc.org/reference/latest/domain/admin/#IOgrids5x5) or finer when required by the Scientific Committee. For longline fisheries, size-frequency data may be reported as part of the Regional Observer Scheme, where such fleets have at least 5% observer coverage of all fishing operations [Res. 15/02; para. 5](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and).

Sampling coverage should be set at a minimum of one (1) fish measured by tonne caught, by fishery and species, with samples being representative of all the periods and areas fished. For each stratum, data coverage -- i.e., the percentage (%) of catch/effort sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates. Additionally, raised estimates of the size samples must be reported to the Secretariat to account for any bias resulting from unrepresentative sampling and the spatio-temporal variability of fishing operations. Documents detailing the sampling and raising procedures must be provided for each fishery and species.

#### Data dimensions

##### Main stratum

-   Month
-   [Grids](../domain/admin/#IOTCgridsCESF)
-   [Species](../domain/biology/#allSpecies)
-   [Sexes](../domain/biology/#sex)
-   [Types of fate](../domain/biology/#typesOfFate)
-   [Fates](../domain/biology/#fates)

##### Original data

-   [Types of data](../domain/data/#types)
-   [Data sources](../domain/data/#sourcesSF)
-   [Data processings](../domain/data/#processingsSF)

##### Source coverage

-   [Estimations](../domain/data/#estimations)
-   [Coverage types](../domain/data/#coverageTypes)
-   [Raisings](../domain/data/#raisings)

##### Measurement

-   [Types of measurement](../domain/biology/#typesOfMeasurement)
-   [Measurements](../domain/biology/#allMeasurementTypes)
-   [Tools](../domain/biology/#allMeasurementTools)

#### Reporting form details

Form [4SF](../forms/#Form_4SF)

<hr style="border:1.5px solid black">
