## Geo-referenced catches and efforts {#CEdataset}

#### Description

Estimates of species-specific retained catches and efforts by fishing fleet, fishery, and space and time strata, including the effort exerted by the support vessels assisting the purse seiners. 

#### Conservation and Management Measures

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) (Annexes I-III) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [15/02](https://www.iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and) (para. 4)  -- _On mandatory statistical reporting requirements for IOTC Contracting Parties and Cooperating Non-Contracting Parties (CPCs)_
- Res. [18/05](https://www.iotc.org/cmm/resolution-1805-management-measures-conservation-billfishes-striped-marlin-black-marlin-blue) (para. 8) -- _On management measures for the conservation of the billfishes: striped marlin, black marlin, blue marlin and Indo-Pacific sailfish_
- Res. [25/08](https://iotc.org/cmm/resolution-2508-conservation-sharks-caught-association-fisheries-managed-iotc) (para. 32) -- _On the conservation of sharks caught in association with fisheries managed by IOTC_
- Res. [25/09](https://iotc.org/cmm/resolution-2509-conservation-shortfin-and-longfin-mako-sharks-caught-association-iotc-fisheries) (para. 5) -- _On the conservation of shortfin and longfin mako sharks caught in association with IOTC fisheries_

##### Retention bans in [longline](#iotclonglinefishery) and [surface](#iotcsurfacefishery) fisheries

- Res. [19/03](https://iotc.org/cmm/resolution-1903-conservation-mobulid-rays-caught-association-fisheries-iotc-area-competence) (para. 3) -- _On the conservation of mobulid species caught in association with fisheries in the IOTC area of competence_
- Res. [25/08](https://iotc.org/cmm/resolution-2508-conservation-sharks-caught-association-fisheries-managed-iotc) (para. 3) -- _On the conservation of sharks caught in association with fisheries managed by IOTC_

#### Contents

- Estimates of fishing effort shall be expressed in units consistent with the recording requirements established by relevant IOTC Conservation and Management Measures](#cmm) and shall be complemented by the number of [fishing operations/sets](#fishingOperation) for [longline fisheries](#iotcLonglineFishery) and [surface fisheries](#iotcSurfaceFishery).

For most gears (e.g., purse seine, longline, gillnet, handline), a fishing operation corresponds to one complete deployment and retrieval of the gear. In [pole-and-line fisheries](#poleAndLineFishery), multiple poles may be operated simultaneously while fishing on the same school. In such cases, the overall fishing activity may constitute a fishing event that includes several individual fishing operations/sets. However, for reporting purposes, effort should be standardised in a manner that ensures comparability across fisheries and consistency with observer coverage requirements.

For coastal fisheries, it is recommended that effort data be submitted using the same effort units as those prescribed for longline and surface fisheries characterised by the same fishing gear.

**Standard effort units by gear group**

| Gear group | Primary effort | Secondary effort | 
| :------------ | :-------------------- | :------------------- |
Gillnets (GI)        | Number of fishing days   | Number of fishing operations/sets |
Hooks and lines (HL) | Number of fishing days   | Number of fishing operations/sets |
Longlines (LL)       | Number of hooks deployed | Number of fishing operations/sets |
Other gears (OT)     | Number of days at sea    | Number of active gears or fishing operations/sets |
Pole-and-lines (PL)  | Number of fishing days   | Number of fishing operations/sets |
Purse seines (PS)    | Number of fishing hours  | Number of fishing operations/sets |

**Additional effort indicators**

Additional units may be considered to refine and standardise the estimation of nominal fishing effort:

i. In gillnet fisheries, the surface area of the nets deployed may better reflect effort intensity by accounting for differences in net length and height;

ii. In hooks and line fisheries, the number of hooks may be used as required for longline fisheries;

iii. In purse seine fisheries, the numbers of successful and null fishing operations, searching time, and surface area explored may complement the information provided by fishing time and the total number of fishing sets. 

**Units not recommended**

From a general perspective, the use of trips as a unit of effort is not recommended, as trip duration may vary widely due to vessel size, fishing success, environmental conditions, or operational constraints (e.g., fuel availability).

Similarly, fishing events may not accurately reflect the level of effort exerted in pole-and-line fisheries where the number of poles operated simultaneously varies between events. For this reason, the fishing operation/set remains the preferred standardised unit for effort reporting wherever feasible.

- Estimates of catches for the IOTC species, common sharks, and other bycatch species. Extrapolated to national monthly catch totals is mandatory (M) for [longline fisheries](#iotclonglinefishery) and [surface fisheries](#iotcsurfacefishery) and optional (O) for [coastal fisheries](#iotccoastalfishery).

For each stratum, the data coverage -- i.e., the percentage (%) of catch/effort sampled -- derived from the coverage type must be reported to assess the representativeness and quality of the estimates. The spatial and temporal resolutions, catch units, and level of extrapolation vary according to the fishery category.

| Category | Temporal resolution | Spatial resolution | Catch unit | Extrapolation | 
| :-------------- | :----------- | :---------- | :------------- | :-------: |
[Surface fisheries](#iotcsurfacefishery)  | Month | [1° grid area](../domain/admin/#IOgrids1x1) | Live weight equivalent | M |
[Longline fisheries](#iotclonglinefishery) | Month or finer for the SC | [5° grid area](../domain/admin/#IOgrids5x5) or finer for the SC | Numbers or live weight equivalent | M |
[Coastal fisheries](#iotccoastalfishery) | Year or finer | [Irregular areas](../domain/admin/#IOTCareasAR) | Numbers or live weight equivalent | O |

Documentation describing the extrapolation procedures (including raising factors for logbook coverage) is also required and must be routinely submitted (Res. [15/02](https://iotc.org/cmm/resolution-1502-mandatory-statistical-reporting-requirements-iotc-contracting-parties-and); para. 4). A template for reporting information on sampling procedures is available in the document [IOTC-2021-WPDCS17-27](https://www.iotc.org/WPDCS/17/27).

#### Reporting Metadata

- [Liaison officer full name](#fcname)
- [Liaison officer email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data Dimensions 

##### Catch Main Elements

- Month
- [Fisheries](../domain/fisheries/#fisheries)
- [Grids](../domain/admin/#IOTCgridsCESF)
- [Estimations](../domain/data/#estimations)
- [Species](../domain/biology/#allSpecies)  
- [Catch units](../domain/fisheries/#catchUnits)

##### Effort Main Elements

- Month
- [Fisheries](../domain/fisheries/#fisheries)
- [Grids](../domain/admin/#IOTCgridsCESF)
- [Estimations](../domain/data/#estimations)
- [Effort units](../domain/fisheries/#effortUnits)

##### Original Data

- [Types of data](../domain/data/#types)
- [Data sources](../domain/data/#sourcesCE)
- [Data processings](../domain/data/#processingsCE)

##### Source Coverage

- [Coverage types](../domain/data/#coverageTypes)
- [Raisings](../domain/data/#raisings)

#### Reporting Form Details

Form [3CE](../forms/#Form_3CE)

<hr style="border:1.5px solid black">
