## Species presence in the catch {#DRdataset}

#### Description

Matrix of presence of species in the retained catches and discards of each fishing fleet by gear group and broad fishery category.

#### Conservation and Management Measures

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) (Annex II) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [18/07](https://www.iotc.org/cmm/resolution-1807-measures-applicable-case-non-fulfilment-reporting-obligations-iotc) (para. 4) -- _On measures applicable in case of non-fulfilment of reporting obligations in the IOTC_ 

#### Contents

Matrix table with species in rows and gear groups in columns. For each species/gear combination, the cell must be filled with either a value of one (1) in case of positive catch or a value of zero (0) in case of absence of catch (i.e., no landing and no discard). Species include IOTC species, mobulid rays, common sharks, and other bycatch species. All gear groups (hooks and lines, pole-and-lines, longlines, purse seines, gillnets, and other gears) are included and further broken down by broad fishery category, i.e., [coastal](#iotccoastalfishery) and [longline](#iotclonglinefishery) or [purse seine](#iotcpurseseinefishery).

#### Reporting Metadata

- [Liaison officer full name](#fcname)
- [Liaison officer email](#fcemail)
- [Organisation name](#orgname)
- [Organisation email](#orgemail)
- [Finalisation date](#findate)
- [Submission date](#subdate)
- [Reporting year](#repyear)
- [Reporting entity](#repentity)
- [Flag state](#repflagstate)

#### Data Dimensions

- [Species](../domain/biology/#allSpecies)
- [Gear groups](../domain/fisheries/#gearGroups)
- [Fishery categories](../domain/fisheries/#fisheryCategories)

#### Reporting Form Details

Form [1DR](../forms/#Form_1DR)

<hr style="border:1.5px solid black">
