# Objectifs généraux {#SectionObjectifs}

La collecte et la diffusion efficaces de données sur les pêcheries sont essentielles pour la conservation et la gestion durable des thons et des espèces apparentées dans l'Océan Indien. La Commission des Thons de l'Océan Indien (CTOI) a identifié plusieurs jeux de données essentiels au suivi des pêcheries de thons et d'espèces apparentées et à l'analyse de l'état et des tendances des populations et des écosystèmes marins qui les soutiennent.

Ces jeux de données doivent être communiqués par les [Parties contractantes de la CTOI et les Parties non contractantes coopérantes](https://iotc.org/fr/apropos/structure-de-la-commission) (CPCs) dans le cadre de l'[Accord de la CTOI](#iotcaccord) mais elles sont également demandées à toute autre partie qui pêche dans la [zone de compétence de la CTOI](#iotcareaofcompetence) pour les espèces gérées par la CTOI. 
  
Depuis sa création en 1996, la CTOI a élaboré et mis en oeuvre plusieurs mesures de conservation et de gestion (MCG) qui comprennent des dispositions spécifiques sur la nature et les caractéristiques des données qui doivent être collectées et communiquées au Secrétariat de la CTOI. Il est de la responsabilité de chaque pays d’établir et d’appliquer des systèmes d’enregistrement et de déclaration des données qui répondent aux critères fixés par la CTOI à travers ses [MCG](#MCG) et le Secrétariat supervise la traitement et la gestion des différents jeux de données qui supportent le processus scientifique de la CTOI.
    
L'objectif principal des directives pour la déclaration des données (DDD) est de fournir un ensemble de règles et de meilleures pratiques au personnel responsable de la collecte et de la déclaration des données halieutiques et biologiques au Secrétariat de la CTOI conformément aux [MCGs](#MCG) en place.

Les DDDs visent à:

1. Présenter aux utilisateurs la terminologie de la CTOI (section [Terminologie](#SectionTerminologie))
2. Fournir le cadre et les normes pour la déclaration des éléments des données ainsi que les métadonnées requises pour leur répertoire et leur gestion (section [Métadonnées](#SectionMétadonnées))
3. Décrirez le contenu de chaque jeu de données tel qu’il figure dans les formulaires de déclaration de la CTOI (section [Jeux de données](#SectionJeuxDeDonnées)), 
4. Présenter la procédure de contrôle de la qualité des données de la CTOI et détailler les vérifications à effectuer sur les métadonnées et les données avant toute soumission (section [Procédure de contrôle de qualité](#SectionQualité))
5. Expliquer les principales caractéristiques du processus de soumission, y compris les détails sur la plateforme de soumission des données, les délais de déclaration, la structure des fichiers à déclarer et la procédure de révision des soumissions historiques (section [Procédure de soumission des données](#SectionSoumission)).

Les directives n'incluent pas les exigences en matière de rapports liées au système d'observation régional (ROS; [Res. 22/04](https://iotc.org/fr/mcg/r%C3%A9solution-2204-sur-un-m%C3%A9canisme-r%C3%A9gional-d%E2%80%99observateurs)) ainsi que la surveillance des navires de pêche autorisés et actifs (Rés. [10/08](https://iotc.org/fr/mcg/r%C3%A9solution-1008-sur-un-registre-des-navires-en-activit%C3%A9-p%C3%AAchant-les-thons-et-l%E2%80%99espadon-dans-la) et Rés. [19/04](https://iotc.org/fr/mcg/r%C3%A9solution-1904-concernant-le-registre-ctoi-des-navires-autoris%C3%A9s-%C3%A0-op%C3%A9rer-dans-la-zone-de)), débarquements et transbordements des produits de la pêche dans les ports ([Res. 16/11](https://www.iotc.org/cmm/resolution-1611-port-state-measures-prevent-deter-and-eliminate-illegal-unreported-and)), et transbordements en mer (Rés. [23/05](https://iotc.org/fr/mcg/r%C3%A9solution-2305-sur-la-mise-en-place-d%E2%80%99un-programme-pour-les-transbordements-des-grands-navires)) qui sont gérés par la [section d'application](https://iotc.org/fr/application/mod%C3%A8les-pour-la-d%C3%A9claration) du Secrétariat.
