---
title: "Guidelines for Reporting Regional Observer Scheme Data to the IOTC"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  officedown::rdocx_document:
    reference_docx: "../../templates/rdoc_template.docx"
  html_document2:
    css: "../../templates/fao_template_simplified.css"
    number_sections: FALSE
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
---
  
```{r general_options, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      tab.cap.pre = "Tab. ", 
                      tab.cap.sep = ". ", 
                      tab.cap.style ="Table Caption", 
                      tab.cap.fp_text = officer::fp_text_lite(italic = FALSE, bold = FALSE), 
                      fig.cap.fp_text = officer::fp_text_lite(italic = FALSE, bold = FALSE),
                      fig.cap = TRUE, 
                      fig.cap.pre = "Fig. ", 
                      fig.cap.sep = ". ", 
                      fig.cap.style = "Caption label", 
                      dpi = 150
                      )
```

```{r child = "en/01_Purposes.Rmd"}
```

```{r child = "en/02_Reporting.Rmd"}
```

```{r child = "en/03_Gear_Specific_Data_Requirements.Rmd"}
```

```{r child = "en/04_SSI_Reporting_Requirements.Rmd"}
```

```{r child = "en/05_Additional_Reporting_Requirements.Rmd"}
```

```{r child = "en/06_Reporting_Resources.Rmd"}
```
